[project]
name = "game-dev"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyglet>=2.0,<3.0",
]

[dependency-groups]
dev = [
    "ruff>=0.9",
    "mypy>=1.14",
]

[tool.ruff]
src=["."]
